spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: sale-service
          uri: lb://sale-service
          predicates:
            - Path=/api/v1/sale/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/user/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/v1/payment/**

server:
  port: 8222

logging:
  level:
    org.springframework.security: DEBUG
