spring:
  application:
    name: sale-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
#
#redis:
#  host: localhost
#  port: 6379
#