spring:
  application:
    name: sale-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/geardotcom
    username: postgres
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

file_upload-dir: C:\truongle_workspace\geardotcom-microservice\images
file_upload-url: http://localhost:8222/api/v1/sale/products
